name: Lint

on:
  pull_request:
    branches: ["*"]

jobs:
  lint:
    name: with eslint
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.20.0]

    steps:
      - uses: actions/checkout@v2
      - uses: elasticdao/actions-yarn@b7b56e2dafbc4bb4d2dcc7025c91b9e900ea33b9
        with:
          cmd: install # will run `yarn install` command
      - uses: elasticdao/actions-yarn@b7b56e2dafbc4bb4d2dcc7025c91b9e900ea33b9
        with:
          cmd: lint # will run `yarn lint` command

