name: Lint

on:
  pull_request:
    branches: ["*"]

jobs:
  lint:
    name: with eslint
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.20.0]

    steps:
      - uses: actions/checkout@v2
      - uses: elasticdao/actions-yarn@43391acf92f467dc0a4c13227241fa92efdea911
        with:
          cmd: install # will run `yarn install` command
      - uses: elasticdao/actions-yarn@43391acf92f467dc0a4c13227241fa92efdea911
        with:
          cmd: lint # will run `yarn lint` command

