name: Lint

on:
  pull_request:
    branches: ["*"]

jobs:
  lint:
    name: with eslint
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.20.0]

    steps:
      - uses: actions/checkout@v2
      - uses: elasticdao/actions-yarn@de10d9ab8d1ae3e32ffc715edb5c7c1ba552204d
        with:
          cmd: install # will run `yarn install` command
      - uses: elasticdao/actions-yarn@de10d9ab8d1ae3e32ffc715edb5c7c1ba552204d
        with:
          cmd: lint # will run `yarn lint` command

