name: Lint

on:
  pull_request:
    branches: ["*"]

jobs:
  lint:
    name: with eslint
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.20.0]

    steps:
      - uses: actions/checkout@v2
      - uses: elasticdao/actions-yarn@d43535b974e6416ee513f9d6d5f708f1395f66d5
        with:
          cmd: install # will run `yarn install` command
      - uses: elasticdao/actions-yarn@d43535b974e6416ee513f9d6d5f708f1395f66d5
        with:
          cmd: lint # will run `yarn lint` command

