name: Lint

on:
  pull_request:
    branches: ["*"]

jobs:
  lint:
    name: with eslint
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.20.0]

    steps:
      - uses: actions/checkout@v2
      - uses: elasticdao/actions-yarn@8fa4b14a000fb12f38921dfdf299063ed9fb9501
        with:
          cmd: install # will run `yarn install` command
      - uses: elasticdao/actions-yarn@8fa4b14a000fb12f38921dfdf299063ed9fb9501
        with:
          cmd: lint # will run `yarn lint` command

